# Generated by Django 4.2.16 on 2025-04-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholars', '0002_cohort_cohortimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarsprogram',
            name='title',
            field=models.CharField(default='none', verbose_name='title given to the program'),
            preserve_default=False,
        ),
    ]
