# Generated by Django 4.2.16 on 2025-04-11 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0026_delete_uploadedimage'),
        ('scholars', '0003_scholarsprogram_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cohort',
            name='image',
        ),
        migrations.AddField(
            model_name='cohort',
            name='cover_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image', verbose_name='O'),
        ),
    ]
