# Generated by Django 4.2.16 on 2025-04-11 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0026_delete_uploadedimage'),
        ('scholars', '0004_remove_cohort_image_cohort_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='female_scholars',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='cohort',
            name='link_to_document',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Link to Document'),
        ),
        migrations.AddField(
            model_name='cohort',
            name='male_scholars',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='cover_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image', verbose_name='Cohort Cover Image'),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Cohort Name'),
        ),
    ]
