# Generated by Django 4.2.16 on 2025-04-10 09:39

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0014_alter_ourteam_our_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationsfundsandscholars',
            name='block',
            field=wagtail.fields.StreamField([('tamplated', 5)], block_lookup={0: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Number of received donations', 'required': True}), 1: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Number of scholars to be supported by the project in this year', 'required': True}), 2: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'The amount raised, in US dollars!', 'required': True}), 3: ('wagtail.blocks.IntegerBlock', (), {'help_text': 'Number of scholars to be supported by the project by 2028', 'required': True}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'This the image that will be the background of the section.', 'required': True}), 5: ('wagtail.blocks.StructBlock', [[('donations', 0), ('scholarsthisyear', 1), ('funds', 2), ('scholars', 3), ('background_image', 4)]], {})}),
        ),
        migrations.AlterField(
            model_name='ourteam',
            name='our_team',
            field=wagtail.fields.StreamField([('templated', 9)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'max_num': 1, 'required': True}), 2: ('wagtail.blocks.CharBlock', (), {'max_length': 255, 'required': True}), 3: ('wagtail.blocks.EmailBlock', (), {'required': True}), 4: ('wagtail.blocks.CharBlock', (), {'min_length': 10, 'required': True}), 5: ('wagtail.blocks.URLBlock', (), {'required': False}), 6: ('wagtail.blocks.CharBlock', (), {'max_length': 30, 'required': True}), 7: ('wagtail.blocks.StructBlock', [[('picture', 1), ('first_name', 2), ('second_name', 2), ('email', 3), ('phone', 4), ('linkedIn', 5), ('role', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {'max_num': 5}), 9: ('wagtail.blocks.StructBlock', [[('block_title', 0), ('title', 0), ('members', 8)]], {})}),
        ),
    ]
