# Generated by Django 5.1.1 on 2024-09-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_sitesettings_inverted_rectangle_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donatepage',
            name='donate_link',
        ),
        migrations.RemoveField(
            model_name='donatepage',
            name='patternship_image',
        ),
        migrations.AddField(
            model_name='donatepage',
            name='donation_embed_code',
            field=models.TextField(blank=True, help_text='Paste your donation form HTML from donorbox.org or similar service here.', null=True, verbose_name='Donation Embed Code'),
        ),
    ]
