# Generated by Django 5.1.1 on 2024-09-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_remove_donatepage_donate_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='email_common_message',
            field=models.CharField(blank=True, help_text='Text for the donate button', max_length=100, null=True, verbose_name='Donate Button Text'),
        ),
    ]
