# Generated by Django 5.1.1 on 2024-09-28 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_sitesettings_email_bunner_image'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='email_bunner_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image', verbose_name='Email bunner Image'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email_common_message',
            field=models.CharField(blank=True, help_text='This message will be shown at the buttom of every system sentt emails', max_length=100, null=True, verbose_name='Common Email message'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, verbose_name='General Telephone line'),
        ),
    ]
