# Generated by Django 5.1.1 on 2024-09-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_sitesettings_email_bunner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='email_common_message',
            field=models.CharField(blank=True, help_text='This message will be shown at the buttom of every system sent emails', max_length=100, null=True),
        ),
    ]
