# Generated by Django 4.2.16 on 2025-04-10 09:39

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_sitesettings_email_common_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerjoinpage',
            name='volunteership_message',
            field=wagtail.fields.RichTextField(help_text='A short message to attract volunteers', null=True),
        ),
    ]
